---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  client_rb:
    environment: local

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[et_verify_app::default]
